# Generated by Django 3.2.13 on 2022-05-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('releaseDate', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('duration', models.CharField(max_length=20)),
                ('recordLabel', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('releaseDate', models.DateTimeField(auto_now=True, null=True)),
                ('duration', models.CharField(max_length=20)),
                ('completeFile', models.FileField(blank=True, null=True, upload_to='')),
                ('previewFile', models.FileField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recordLabel', models.CharField(max_length=128)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='apiMusic.album')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stageName', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('nationality', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('biography', models.CharField(max_length=128)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singers', to='apiMusic.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singersS', to='apiMusic.song')),
            ],
        ),
    ]
