# Generated by Django 3.2.13 on 2022-05-16 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cdPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numTracks', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('image', models.TextField()),
                ('duration', models.DurationField()),
                ('recordLabel', models.CharField(max_length=128)),
                ('releaseDate', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Genre of music (i.e. Blues)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stageName', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('nationality', models.CharField(max_length=128)),
                ('image', models.TextField()),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('completeFile', models.CharField(max_length=128)),
                ('previewFile', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recordLabel', models.CharField(max_length=128)),
                ('image', models.TextField()),
                ('releaseDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiMusic.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=20)),
                ('completeFile', models.CharField(max_length=128)),
                ('previewFile', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recordLabel', models.CharField(max_length=128)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiMusic.album')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiMusic.genre')),
                ('singers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiMusic.singer')),
            ],
        ),
        migrations.CreateModel(
            name='SinglesSingers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SingerWithSingles', to='apiMusic.singer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SongWithSingers', to='apiMusic.singlesong')),
            ],
        ),
        migrations.AddField(
            model_name='singlesong',
            name='singerSingle',
            field=models.ManyToManyField(through='apiMusic.SinglesSingers', to='apiMusic.Singer'),
        ),
        migrations.AddField(
            model_name='album',
            name='singerA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiMusic.singer'),
        ),
    ]
