# Generated by Django 4.0.3 on 2022-05-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.TextField(),
        ),
    ]
