# Generated by Django 3.2.13 on 2022-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlesong',
            name='completeFile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='singlesong',
            name='previewFile',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
