# Generated by Django 3.2.13 on 2022-05-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0002_alter_album_duration_alter_album_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Genre of music (i.e. Blues)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='singer',
            name='album',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='song',
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiMusic.singer'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='biography',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiMusic.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='completeFile',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='previewFile',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiMusic.genre'),
        ),
    ]
