# Generated by Django 3.2.13 on 2022-05-07 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0003_auto_20220506_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiMusic.singer'),
        ),
    ]
