# Generated by Django 3.2.13 on 2022-05-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0004_song_singer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='singers',
        ),
    ]
