# Generated by Django 3.2.13 on 2022-05-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0005_rename_singer_song_singers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='duration',
            field=models.DurationField(),
        ),
    ]
