# Generated by Django 3.2.13 on 2022-05-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0006_auto_20220512_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='stock',
        ),
    ]
