# Generated by Django 3.2.13 on 2022-05-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0007_remove_album_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
