# Generated by Django 3.2.13 on 2022-05-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0008_album_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cdPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
