# Generated by Django 3.2.13 on 2022-05-12 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0010_auto_20220512_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='releaseDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
