# Generated by Django 3.2.13 on 2022-05-12 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0012_alter_album_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='singer',
            new_name='singerA',
        ),
    ]
