# Generated by Django 3.2.13 on 2022-05-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0013_rename_singer_album_singera'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='numTracks',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
