# Generated by Django 3.2.13 on 2022-05-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0015_auto_20220514_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='biography',
            field=models.TextField(),
        ),
    ]
