# Generated by Django 3.2.13 on 2022-05-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0016_alter_singer_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlesong',
            name='previewFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
