# Generated by Django 3.2.13 on 2022-05-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMusic', '0017_alter_singlesong_previewfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlesong',
            name='previewFile',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
